---
title: "Proyecto grupal: Un clima estresante"
---

## Introducción

SILO (Scientific Information for Land Owners) es una base de datos en línea australiana que
proporciona datos climáticos.
Administrada por el Departamento de Agricultura y Pesca de Queensland,
SILO ofrece acceso a una amplia gama de datos meteorológicos y climáticos históricos y
actuales para diversas aplicaciones en la agricultura,
la investigación, la gestión de recursos naturales y la planificación ambiental.

Los datos proporcionados por SILO incluyen variables como temperatura, precipitación,
humedad relativa, evaporación y radiación solar.

Los datos provistos se encuentran en la carpeta `datos/boonah` y están organizados
por año. Dentro de cada carpeta anual hay tres conjuntos de datos con registros diarios
proporcionados por SILO para las coordenadas `(-27.9927, 152.6906)`,
que se encuentran en las afueras de Boonah, una ciudad rural en Queensland, Australia:

* `lluvias.csv`: información sobre precipitaciones diarias.
* `atmosfera.csv`: información sobre temperaturas y humedad relativa.
* `energia.csv`: información sobre evaporación y radiación.

Las columnas en estos conjuntos de datos son las siguientes:

En `lluvias.csv`:

* **fecha**: Fecha en que se realizó la medición en formato `YYYY-MM-DD`.
* **lluvia**: Cantidad de lluvia caída en el día (mm).

En `atmosfera.csv`:

* **fecha**: Fecha en que se realizó la medición en formato `YYYY-MM-DD`
(4 dígitos para el año, 2 para el mes y 2 para el día).
* **t_min**: Temperatura mínima registrada en el día (°C).
* **t_max**: Temperatura máxima registrada en el día (°C).
* **hr_t_min**: Humedad relativa en el momento que se registra la temperatura mínima (%).
* **hr_t_max**: Humedad relativa en el momento que se registra la temperatura máxima (%).

En `energia.csv`:

* **fecha**: Fecha en que se realizó la medición en formato `YYYY-MM-DD`
(4 dígitos para el año, 2 para el mes y 2 para el día).
* **evaporación**: Evaporación (mm).
* **radiación**: Exposición solar en Megajulios por metro cuadrado (MJ / m²).

## Actividades

A continuación, se listan preguntas a responder y actividades a realizar:

* ¿Cuántas observaciones hay en el conjunto de datos? ¿Cuántas para cada año?
* ¿Hay datos faltantes?
* ¿Cuál es la cantidad total de lluvia caída en la zona? ¿Y cuánto se corresponde a cada año?
Realice un gráfico de barras.
* Visualice la cantidad de lluvia por mes y año en un gráfico de líneas.
* Obtenga uno o varios gráficos que muestre(n) la evolución de la temperatura mínima y máxima a lo largo del tiempo.
* Obtenga un gráfico que permita ver la asociación entre la temperatura mínima y máxima.
* Calcule la amplitud térmica, es decir, la diferencia entre la mayor y menor temperatura diaria.
* Visualice el comportamiento de la amplitud térmica:
    * Globalmente y a lo largo del tiempo.
    * ¿Hay alguna asociación entre la amplitud térmica y la temperatura mínima o máxima del día?
    * ¿Hay alguna asociación entre la amplitud térmica y la cantidad de precipitaciones que se registran?
* ¿Cuál es el mes (o los meses) que suelen recibir mayor radiación? Aquí puede utilizar simple medidas resumen o un gráfico,
lo que crea conveniente.
* ¿En qué mes a lo largo de los 5 años de datos se observó el mayor nivel de evaporación?

### Días de estrés

Los "días de estrés" se refieren a días en que las condiciones ambientales son desfavorables para el crecimiento óptimo de los cultivos.
Un factor que determina el nivel de estrés es la temperatura.
Cuando estas son extremas, pueden causar estrés térmico en los cultivos.
En este ejercicio nos interesa determinar días de estrés térmico utilizando como indicador a la temperatura máxima.
Se establece una temperatura de referencia de 32 grados centígrados.

* Determine los días de estrés en base a la temperatura máxima.
Para ello, cree una nueva columna en el data frame que se llame `"estrés"` y que contenga valores `False` y `True` o valores `0` y `1`.
* ¿Cuántos días de estrés térmico se observan entre el `2019-10-14` y el `2019-12-03`?
**Ayuda**: Se puede filtrar el conjunto de datos para conservar solo las filas dentro del rango de fechas y luego sumar la cantidad de días con estrés.
* Obtenga la cantidad de días de estrés térmico por mes a lo largo de los 5 años y visualícelo en un gráfico de línea.

Además, elabore una función que, dado el conjunto de datos, una fecha de inicio y una fecha de fin,
devuelva la cantidad de días de estrés térmico dentro del rango de fechas indicado.

### Déficit de presion de vapor

El déficit de presión de vapor (VPD, por sus siglas en inglés) es una medida de la
diferencia entre la cantidad de humedad en el aire y la cantidad máxima de humedad que el aire puede contener a una temperatura específica.
Se calcula restando la presión de vapor actual del aire ($vp_a$) de la presión de vapor de saturación ($vp_s$) a la misma temperatura.
Su fórmula es:

$$
\text{VPD} = vp_s - vp_a
$$

A su vez, para calcular la **presión de vapor de saturación** se puede usar la Ecuación de Tetens:

$$
vp_s = 0.61078 \times \text{exp}\left(\frac{17.27 \times T}{T + 237.3}\right)
$$

donde $T$ es temperatura en grados centígrados.
Por ejemplo, para una temperatura de 25 grados centígrados la presión de vapor de saturación $vp_s$ es:

$$
0.61078 \times \text{exp}\left(\frac{17.27 \times 25}{25 + 237.3}\right) = 3.16
$$

El resultado se mide en **kilopascales (kPa)**.

Por otro lado, para calcular la **presión de vapor actual**, se puede utilizar la siguiente fórmula:

$$
vp_a = vp_s \times \frac{\text{Humedad relativa}}{100}
$$

Por ejemplo, si la temperatura es de 27.5 °C y la humedad relativa es del 78%, el VPD se obtiene de la siguiente manera:

**1. Cálculo de presión de vapor de saturación**

$$
vp_s = 0.61078 \times \text{exp}\left(\frac{17.27 \times 27.5}{27.5 + 237.3}\right) \approx 3.67 \ \text{kPa}
$$

**2. Cálculo de presión de vapor actual**

$$vp_a = vp_s \times \frac{\text{Humedad relativa}}{100} =  3.67 \times \frac{78}{100} \approx 2.86 \ \text{kPa}$$

**3. Cálculo de presión de VPD**

$$\text{VPD} = vp_s - vp_a = 3.67115 - 2.863497 \approx 0.81 \ \text{kPa}$$

Calcule el déficit de presión de vapor en el momento que se registró la temperatura máxima.
Luego, obtenga una nueva variable que clasifique a los días de acuerdo a la siguiente regla:

* VPD entre **0 y 0.5 kPa**: Condiciones muy húmedas.
* VPD entre **0.5 y 1.0 kPa**: Condiciones moderadamente húmedas.
* VPD entre **1.0 y 2.0 kPa**: Condiciones semiáridas.
* VPD entre **2.0 y 3.0 kPa**: Condiciones áridas.
* VPD mayor a **3.0 kPa**: Condiciones extremadamente secas.

y reporte el porcentaje de días en cada condición.
Si lo cree conveniente, vuelque esa información en un gráfico apropiado.

