---
title: "đźŞž AutoevaluaciĂłn"
number-depth: 3
toc-depth: 3
---

## Variables

1.  ÂżQuĂ© valor contiene la variable `contador` luego de ejecutar el siguiente cĂłdigo?

    ```python
    contador = 20
    contador + 1
    ```

1. Complete la siguiente tabla indicando si el nombre es vĂˇlido para una variable de Python.

    |     Nombre        | ÂżVĂˇlido? | JustificaciĂłn |
    |:-----------------:|:--------:|:-------------:|
    | `balance`         |          |               |
    | `balanceActual`   |          |               |
    | `balance-actual`  |          |               |
    | `balance actual`  |          |               |
    | `balance_actual`  |          |               |
    | `mis.datos`       |          |               |
    | `0cuenta`         |          |               |
    | `cuenta0`         |          |               |
    | `_cuenta`         |          |               |
    | `SPAM`            |          |               |
    | `cantidad$`       |          |               |


## NĂşmeros

1. ÂżCuĂˇl es el tipo de `10 / 2`? ÂżPor quĂ©?

1. ÂżCuĂˇl es el tipo de `5 * 2`? ÂżPor quĂ©?

1. ÂżPor quĂ© `5 == 5.0` es `True`?

## Booleanos

1. ÂżCuĂˇl es el resultado de las siguientes expresiones? ÂżPor quĂ©?

    ```python
    False or not False
    ```
    ```python
    not (True and True)
    ```

    ```python
    not True and True
    ```

    ```python
    "True" != True
    ```

    ```python
    10 > 5 + 3
    ```

    ```python
    None is None
    ```

    ```python
    False is False
    ```

1. Ejecute lĂ­nea por lĂ­nea los siguientes bloques y analice los resultados.

    ```python
    int(True) * 50
    True * 50
    ```

    ```python
    1 is True
    bool(1) is True
    id(True)
    id(bool(1))
    id(bool(1024))
    ```

1. ÂżCuĂˇles son los 3 operadores booleanos?

## Cadenas de caracteres

1. ÂżPor quĂ© la siguiente comparaciĂłn resulta en `True`?

    ```python
    "spam" + "spamspam" == "spam" * 3
    ```

1. ÂżPor quĂ© la siguiente expresiĂłn resulta en un error? ÂżCĂłmo se puede arreglar?

    ```python
    "Me comĂ­ " + 6 + " panchos."
    ```

1. ÂżEncuentra algo extraĂ±o en la siguiente expresiĂłn? ÂżCĂłmo la mejorarĂ­a?

    ```python
    materia = "ProgramaciĂłn 2"
    print("ÂˇSean bienvenidos a la materia {materia}!")
    ```

1. Explique por quĂ© es redundante utilizar `str()` en el siguiente bloque de cĂłdigo:

    ```python
    x, y = 10, 20
    print(f"La suma de {str(x)} y {str(y)} es: {str(x + y)}.")
    ```

1. Considere el siguiente bloque de cĂłdigo:

    ```python
    mensaje = "Hola, ÂżcĂłmo estes?"
    mensaje[-3] = "Ăˇ"
    ```

    - ÂżCuĂˇl es la intenciĂłn detrĂˇs del programa?
    - ÂżPor quĂ© no funciona?
    - ÂżCĂłmo podrĂ­a arreglarlo? Alerta: la soluciĂłn no es muy elegante.

1. ÂżCuĂˇl es el resultado de `list("abcdefgh")`? ÂżPor quĂ©?

1. ÂżPor quĂ© `set("abcde")` es distinto de `{"abcde"}`?

## Funciones

1. ÂżCuĂˇl es la diferencia entre una funciĂłn y una llamada a funciĂłn?

1. ÂżCuĂˇl es el valor que devuelve una funciĂłn que no tiene `return`?

1. ÂżCuĂˇndo se ejecuta el cĂłdigo dentro de una funciĂłn: cuando la funciĂłn se define o cuando se la llama? Considere la siguiente funciĂłn:

    ```python
    def suma(x, y):
        print(100 / 0)
        return x + y
    ```

    Luego, ejecute el siguiente bloque:

    ```python
    suma(2, 4)
    ```

## Listas

1. ÂżQuĂ© es `[]`? ÂżCuĂˇl es el resultado de `len([])`?

1. ÂżPor quĂ© la siguiente expresiĂłn resulta en `False`? Ayuda: use la funciĂłn `id()`.

    ```python
    [] is []
    ```

1. ÂżPor quĂ© se obtiene un error en el siguiente bloque de cĂłdigo?

    ```python
    l = []
    l[0]
    ```

1. Si `[0][0]` devuelve `0`, Âżpor quĂ© `[1][1]` no devuelve `[1]`?

1. ÂżCuĂˇl es el valor de `x` en el siguiente bloque de cĂłdigo? ÂżPor quĂ©?

    ```python
    l = ["hola", "hola hola", "hasta luego"]
    x = l.remove("hola")
    ```

1. ÂżCĂłmo le asignarĂ­a el valor `"hola"` como el tercer valor en una lista almacenada en una variable
llamada `cosas`? Asuma que `cosas` contiene `[2, 4, 6, 8, 10]`.

1. Asuma que `letras` contiene la lista `["a", "b", "c", "d"]`:
    - ÂżA quĂ© evalĂşa `letras[-1]`?
    - ÂżA quĂ© evalĂşa `letras[:2]`?
    - ÂżA quĂ© evalĂşa `letras[int(int('3' * 2) // 11)]`? ÂżEs necesario usar dos veces `int()`?

1. Asuma que `bartulos` contiene la lista `[3.14, "casa", 11, "casa", True]`:
    - ÂżA quĂ© evalĂşa `bartulos.index("casa")`? ÂżPor quĂ©?
    - ÂżCĂłmo queda la lista en `bartulos` despuĂ©s de ejecutar `bartulos.append(99)`?
    - ÂżCĂłmo queda la lista en `bartulos` despuĂ©s de ejecutar `bartulos.remove("casa"')` ?ÂżPor quĂ©?

1. ÂżCuĂˇles son los operadores para la concatenaciĂłn y la replicaciĂłn de listas?

1. ÂżCuĂˇl es la diferencia entre los mĂ©todos `append()` e `insert()` de las listas?

1. ÂżCuĂˇles son dos formas de eliminar valores de una lista?

1. El siguiente bloque de cĂłdigo imprime `['a', 'b', True, 30]`. ÂżPor quĂ©?

    ```python
    cosas = ["a", "b", True]
    bartulos = cosas
    bartulos.append(20 + 10)
    print(cosas)
    ```

1. Considere el siguiente bloque de cĂłdigo:

    ```python
    marcas = ["Milka", "Cofler", "Ăguila", "Cadbury", "Lindt", "Toblerone", "After Eight"]
    marcas[2:5]
    ```

    que correctamente muestra `["Ăguila", "Cadbury", "Lindt"]`.
    ÂżPor quĂ© el siguiente bloque de cĂłdigo no funciona?

    ```python
    marcas = ["Milka", "Cofler", "Ăguila", "Cadbury", "Lindt", "Toblerone", "After Eight"]
    indices = 2:5
    marcas[indices]
    ```

## Tuplas

1. ÂżPor quĂ© la tupla no implementa un mĂ©todo similar al mĂ©todo `.extend()` de las listas?

1. Las tuplas de Python son conocidas por ser inmutables. Por ejemplo, el siguiente bloque de cĂłdigo
resulta en un error:

    ```python
    tupla = (1, 2, 3)
    tupla[1] = 10
    ```

    Sin embargo, el siguiente bloque no arroja ningĂşn error y pareciera que se logra modificar la 
    tupla exitosamente:

    ```python
    bartulos = ["Hola", 10, None]
    tupla = (1, bartulos, 3)

    tupla[1].append("ÂˇSorpesa!")

    print(tupla)
    ```

    ÂżQuĂ© pasĂł?

## Diccionarios

1. ÂżCĂłmo se escribe en cĂłdigo un diccionario vacĂ­o?
1. ÂżCĂłmo se ve un diccionario que tiene la clave `"cosa"` y el valor `15`?
1. ÂżCuĂˇl es la principal diferencia entre un diccionario y una lista?
1. ÂżQuĂ© ocurre si se intenta acceder a `bartulos["cosa"]` cuando `bartulos` es `{"coso": 100}`?
1. Si un diccionario estĂˇ almacenado en `bartulos`, ÂżcuĂˇl es la diferencia entre las siguientes
expresiones?

    ```python
    "cosa" in bartulos
    "cosa" in bartulos.keys()
    ```

1. Suponga el diccionario `datos = {"nombre": "Juan"}`.
ÂżPor quĂ© la siguiente expresiĂłn resulta en `False`?

    ```python
    "Juan" in datos
    ```


## Control de flujo

### Condicionales

1. Explique quĂ© es una condiciĂłn y en quĂ© situaciones se utilizarĂ­a.

1. Identifique los tres bloques de cĂłdigo en el siguiente ejemplo:

    ```python
    codigo = 0

    if codigo == 10:
        print("mensaje 1")
        if codigo > 5:
            print("mensaje 2")
        else:
            print("mensaje alternativo")
        print("mensaje final")

    print("Fin del programa")
    ```

    ÂżTienen sentido las comparaciones utilizadas?

1. ÂżCuĂˇl es el problema con el siguiente programa? Proponga una soluciĂłn.

    ```python
    numero = 10
    if numero < 0:
        print(f"El numero {numero} es negativo")
    elif numero < -5:
        print(f"El numero {numero} es menor a -5")
    elif numero > 0:
        print(f"El numero {numero} es positivo")
    else:
        print(f"El numero {numero} es 0")
    ```

### Bucles

1.  Considere el siguiente programa:

    ```python
    for i in range(10):
        print(i)
    ```

    Escriba un programa que realice la misma tarea utilizando un bucle `while`.

1. ÂżCuĂˇl es la diferencia entre `range(10)`, `range(0, 10)` y `range(0, 10, 1)` en un bucle `for`?

1. Suponga que `numeros` es una lista que contiene numeros enteros, Âżen quĂ© se diferencian los
siguientes bloques de cĂłdigo?

    ```python
    for i in numeros:
        if i % 2 == 0:
            break
        print(i)
    ```

    ```python
    for i in numeros:
        if i % 2 == 0:
            continue
        print(i)
    ```

1. ÂżEs posible re-escribir el siguiente bloque de cĂłdigo usando `while True`? ÂżQuĂ© modificaciones
habrĂ­a que hacer?

    ```python
    suma = 0
    i = 0
    while suma <= limite:
        suma += numeros[i]
        i += 1
    ```