---
title: Aprobación
---

## Instancias de evaluación

*  **Examen parcial**: individual y en computadora.
Hay un recuperatorio, de similares características, que reemplaza la nota del parcial.

*  **Trabajos prácticos** (2): se realizan tanto en clase como fuera de ella,
en grupos de dos o tres integrantes. Se entrega el código desarrollado, un resumen ejecutivo y se presenta oralmente en clase.

Todas las instancias se califican en una escala de 0 a 10 y se aprueban con 6.

## Condiciones de aprobación

**Promoción**
: Quienes aprueben el parcial individual (con nota $\text{PI}$), el trabajo práctico grupal 1
(con nota $\text{TP1}$) y el trabajo práctico grupal 2 (con nota $\text{TP2}$),
adquieren la condición de estudiante promovido y su nota final se calcula como
$\frac{1}{3} \times (\text{PI} + \text{TP1} + \text{TP2})$.


**Regularidad**
: Quienes aprueben el parcial individual (o su recuperatorio) y solo uno de los trabajos prácticos grupales,
adquieren la condición de estudiante regular.

**Libres**
: Quienes no aprueben el parcial individual (ni su recuperatorio) o ninguno de los dos trabajos prácticos grupales,
adquieren la condición de estudiante libre.

