---
title: Uso de Inteligencia Artificial
---

Las herramientas de Inteligencia Artificial (IA) son muy poderosas y pueden ayudarte a
resolver de manera efectiva problemas de todo tipo, especialmente problemas de programación.
De hecho, seguramente la IA pueda resolver todos los ejercicios que se presenten en esta materia por vos.
El punto es que no tiene sentido cursar la materia si te vas a limitar a copiar y pegar enunciados en un chat.
A corto plazo, te puede dar una sensación atractiva de satisfacción y alivio (¿a quién no le gusta tener la práctica resuelta?),
pero a mediano y largo plazo puede contribuir a aumentar tu frustración cuando aparezca
un problema que la IA o bien no resuelve, o no lo hace de la mejor manera,
y vos no logras comprender ni resolver por cuenta propia.

Ahora bien, es innegable que en el mundo profesional las herramientas de IA se usan muchísimo.
Ayudan de verdad a resolver problemas que quizá no podríamos abordar por nuestra cuenta,
o que podríamos resolver, pero a un costo de tiempo mucho mayor.
Por eso, aprender a usarlas sí que tiene un valor real.

Por otro lado, cuando la tendencia a siempre responder, y de manera complaciente, de los modelos
de IA se combinan con nuestro sesgo de automatización, es fácil caer en una encerrona cognitiva.
En esa situación, podemos aceptar sin suficiente juicio lo que la herramienta propone y
perder de vista si realmente entendemos lo que está pasando y, sobre todo, si la solución que se obtiene es satisfactoria.
Salir de esa encerrona, por ahora, sigue siendo parte del trabajo humano.

Para extraer lo mejor de estas herramientas, entonces, es clave conocer el problema que se está resolviendo.
Si vamos a usarlas para programar en Python (o cualquier otro lenguaje),
necesitamos contar con un dominio sólido del lenguaje y de los fundamentos de la programación.

En otras palabaras, en esta materia no estamos en contra del uso de herramientas de IA.
Todo lo contrario. Creemos que pueden ser muy valiosas en el trabajo profesional y también pueden aportar al aprendizaje.
Sin embargo, la base propia de conocimientos necesaria para usar la IA de manera efectiva
solo se construye atravesando el proceso de aprendizaje.
La IA no puede reemplazar ese proceso porque es personal.
Con ese objetivo, dejamos estas recomendaciones generales para el uso de IA durante la materia:

- En vez de copiar y pegar el enunciado de un ejercicio en un chat, describile con tus palabras:
    - de qué se trata el ejercicio que estás trabajando
    - qué avances hiciste hasta ahora
    - qué parte no entendés
    - tu código y los errores, si los hay.

    Es mejor usar la IA como un tutor que te guía, que como un particular que realiza la tarea por vos.
- Del mismo modo que mirar videos de cocina no te hace buen chef,
copiar y pegar código tampoco te convertirá en buen programador.
Cuando la IA te devuelva código, no copies y pegues ese código en el editor de manera automática.
Transcribilo manualmente, aunque pese, siendo crítico de lo que la IA te provee:
    - ¿por qué hace este paso?
    - ¿podría escribir esta parte del programa de otra manera?
    - ¿es necesario agregar este comentario?
    - ¿tiene sentido documentar tan exhaustivamente esta función auxiliar?
- Copiar y pegar texto para dar la impresión que dominas un tema tampoco te ayuda a aprender.
El proceso de escritura enriquece y solidifica el entendimiento sobre un tema.
Por eso se recomienda no utilizar la IA inmediatamente a la hora de redactar respuestas o párrafos enteros.
Una vez que elaboraste al menos un borrador de tu respuesta
(por ejemplo, un punteo con los puntos principales en un orden presuntamente correcto)
se puede utilizar la IA para buscar expresiones alternativas, corregir errores gramaticales,
adaptar estilo y/o tono y, en general, obtener una segunda opinión y revisión general del texto elaborado.

La distinción clave es si la IA contribuye a tu aprendizaje o si está realizando el trabajo intelectual que se espera que vos realices.
En caso de duda, una regla orientadora es preguntarse: ¿puedo explicar y defender con palabras propias todo lo que estoy entregando?
